spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:
  jpa:
    show-sql: true
    hibernate.format_sql: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

