spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/netflix-catalog
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate.format_sql: true
  zipkin:
    baseUrl: http://localhost:9411/
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/